### ISSUE TITLE
The classe "pxb-drawer-nav-item-depth" is not applied correctly when menu data is not available immediately

### ISSUE THREAD

**Issue by mikaelhassam** [brightlayer-ui/angular-component-library#356]
#### Describe the bug
In the linked angular project (nav-item-bug.zip), we can see that the classes `pxb-drawer-nav-item-depth-{depth}` are not applied to the nav-items when the data comes from an observable and is not immediately available at the moment a pxb-drawer-nav-group is created. This is explained by the code here: https://github.com/pxblue/angular-component-library/blob/269d8dc892f7ced14806bf3d2f24e45ca1aadc1f/components/src/core/drawer/drawer-body/nav-group/drawer-nav-group.component.ts#L83 

#### What is the expected behavior?
When the data for the menu is updated, the nav-items should be updated correctly

#### What are the steps to reproduce?
Open the linked project [nav-item-bug.zip](https://github.com/pxblue/angular-component-library/files/7383195/nav-item-bug.zip) and look at the screenshot below

#### Screenshots or links to minimum reproduction example
![Screenshot 2021-10-20 131844](https://user-images.githubusercontent.com/59676212/138143897-09177c16-16f2-4054-a067-e2ea7f5b0eca.jpg)

**Comment by emclaug2** [comment]
Thank you for your patience on this issue, we've just finished up our rebranding to Brightlayer UI. 

Looking closer at this issue, the depth of the Nav Items is calculated on `afterContentInit` which doesn't work correctly whenever the children of the NavGroup are loaded async.   I view this limit as more of an exception since most apps will have their routes known ahead of time, but there's also some alternatives that can work to achieve something very similar.

Idea 1: 
Someone who is loading async navigation items can put classes on these items manually.

`<blui-drawer-nav-item
        [hidePadding]="false"
        *ngFor="let navItem of incorrectExample$ | async"
        [title]="navItem.title"
        class='depth1'
      >
        <blui-drawer-nav-item
          *ngFor="let nestedItem of navItem.items"
          [title]="nestedItem.title"
           class='depth2'
        >
          <blui-drawer-nav-item
            *ngFor="let deepItem of nestedItem.items"
            [title]="deepItem.title"
            class='depth3'
          >
          </blui-drawer-nav-item>
        </blui-drawer-nav-item>
      </blui-drawer-nav-item>
`

Idea 2:
We could update the `depth` variable to be an @Input so users can provide the depth in situations where the component cannot. 
`
<blui-drawer-nav-item
        [hidePadding]="false"
        *ngFor="let navItem of incorrectExample$ | async"
        [title]="navItem.title"
        [depth]="1"
      >
        <blui-drawer-nav-item
          *ngFor="let nestedItem of navItem.items"
          [title]="nestedItem.title"
          [depth]="2"
        >
          <blui-drawer-nav-item
            *ngFor="let deepItem of nestedItem.items"
            [title]="deepItem.title"
            [depth]="3"
          >
          </blui-drawer-nav-item>
        </blui-drawer-nav-item>
      </blui-drawer-nav-item>
`

**Comment by emclaug2** [comment]
I've got a solution working, will push out a beta package soon to test it out.

**Comment by emclaug2** [comment]
@mikaelhassam This has been fixed in the latest version of our component library; thank you for your patience!

https://www.npmjs.com/package/@brightlayer-ui/angular-components/v/6.0.2

**Comment by mikaelhassam** [comment]
Thanks a lot !

Mikael Hassam
